# Generated by Django 3.1.3 on 2020-12-01 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='title',
            new_name='caption',
        ),
    ]
